version: '3.8'

services:

  database:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - "8000:8000"
    env_file:
      - .env